Namespaces:
  =: io.murano.resources
  sys: io.murano.system
  std: io.murano

Name: FiwareMuranoInstance

Extends:
  - ConfLangInstance

Properties:
  nid:
    Contract: $.string()
    Usage: Out


Methods:
 prepareUserData:
    Body:
      - $environment: $.find(std:Environment).require()
      - $resources: new(sys:Resources)
      - $supportScript: $resources.string('support.sh')
      - $region: config(home_region)
      - $supportReplacements:
          "%REGION%": $region
      - $userData: $.generateUserData() + $supportScript.replace($supportReplacements)
      - $metadata: {"region" : $region, "nid": $.nid}
      - $.addMetadata($metadata)
      - Return:
         data: $._generateInstanceConfigResources($userData)
         format: RAW

 addNid:
    Arguments:
      - nid_in:
          Contract: $.string()
    Body:
      $.nid: $nid_in

 addMetadata:
    Arguments:
      - metadata:
          Contract: {}
    Body:
      - $environment: $.find(std:Environment).require()
      - $template:
              resources:
                $.name:
                  properties:
                    metadata: $metadata
      -  $template: $environment.stack.current().mergeWith($template)
      -  $environment.stack.updateTemplate($template)

 _generateInstanceConfigResources:
    Arguments:
      - userData:
          Contract: $.string().notNull()
    Body:
      - $environment: $.find(std:Environment).require()
      - $cloudConfigData: $.generateCloudConfig()
      - $bootConfigResourceName: format('boot_config_{0}', $.name)
      - $bootScriptResourceName: format('boot_script_{0}', $.name)
      - $userDataResourceName: format('user_data-{0}', $.name)
      - $template:
          resources:
            $bootConfigResourceName:
              type: 'OS::Heat::CloudConfig'
              properties:
                cloud_config: $cloudConfigData
            $bootScriptResourceName:
              type: 'OS::Heat::SoftwareConfig'
              properties:
                group: ungrouped
                config: $userData
            $userDataResourceName:
              type: 'OS::Heat::MultipartMime'
              properties:
                parts:
                - config: {get_resource: $bootConfigResourceName}
                - config: {get_resource: $bootScriptResourceName}

      - $environment.stack.updateTemplate($template)
      - Return: {get_resource: $userDataResourceName}
