site_name: FIWARE-Murano
site_url: https://fiware-murano.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-murano.git
site_description: FIWARE Murano Documentation
docs_dir: doc/manuals
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
google_analytics: ['UA-82830081-1', 'fiware-murano.readthedocs.io']
pages:
  - ['index.md', 'Welcome to FIWARE Murano']
  - ['admin.md', 'FIWARE Murano Admin Guide']
  - ['user.md', 'FIWARE Murano User Guide']
  - ['docker.md', 'Working with Docker']

