site_name: FIWARE-Murano
site_url: https://fiware-murano.readthedocs.org
repo_url: https://github.com/telefonicaid/fiware-murano.git
site_description: FIWARE Murano Documentation
site_dir: html
docs_dir: doc
markdown_extensions: [toc, fenced_code]
use_directory_urls: false
theme: readthedocs
index_page: [index.md, README.md]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - ['index.md', 'Welcome to FIWARE Murano']
  - ['admin.md', 'FIWARE Murano Admin Guide']
  - ['user.md', 'FIWARE Murano User Guide']
  - ['docker.md', 'Working with Docker']

